fun main() {
    println("Enter student's Enrollment Number : ")
    var enno = readLine()
    println("Enter student's Name : ")
    var name = readLine()
    println("Enter student's Branch  : ")
    var branch = readLine()
    println("Enter student's Class  : ")
    var cls = readLine()
    println("Enter student's Batch : ")
    var batch = readLine()
    println("Enter student's College Name  : ")
    var cname = readLine()
    println("Enter student's University : ")
    var uname = readLine()
    println("Enter student's Age : ")
    var age = readLine()

    println()
    println("******************************")

    println("Student's Data: ")
    println("Enrollment Number : $enno")
    println("Name : $name")
    println("Branch : $branch")
    println("Class : $cls")
    println("Batch : $batch")
    println("College Name : $cname")
    println("University Name : $uname")
    println("Age : $age")
}
